import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Lang = "zh" | "en";

type Dict = Record<string, { zh: string; en: string }>;

const dict: Dict = {
  // ===== Navbar =====
  "nav.jobs": { zh: "岗位推荐", en: "Jobs" },
  "nav.match": { zh: "简历匹配", en: "Match" },
  "nav.rewrite": { zh: "简历改写", en: "Rewrite" },
  "nav.interview": { zh: "面试辅导", en: "Interview" },
  "nav.dashboard": { zh: "数据看板", en: "Dashboard" },
  "nav.signin": { zh: "登录", en: "Sign In" },
  "nav.signinSignup": { zh: "登录 / 注册", en: "Sign In / Up" },
  "nav.signout": { zh: "退出登录", en: "Sign Out" },
  "nav.loggedIn": { zh: "已登录", en: "Signed In" },
  "nav.dashboardItem": { zh: "数据看板", en: "Dashboard" },
  "nav.langTooltip": { zh: "切换到英文", en: "Switch to Chinese" },

  // ===== Auth Page =====
  "auth.welcomeBack": { zh: "欢迎回来", en: "Welcome Back" },
  "auth.createAccount": { zh: "创建账号", en: "Create Account" },
  "auth.signinDesc": { zh: "登录以访问你的求职数据看板", en: "Sign in to access your job-search dashboard" },
  "auth.signupDesc": { zh: "注册后即可保存简历分析与面试记录", en: "Sign up to save your resume analyses and interviews" },
  "auth.signinTab": { zh: "登录", en: "Sign In" },
  "auth.signupTab": { zh: "注册", en: "Sign Up" },
  "auth.fullName": { zh: "姓名", en: "Full Name" },
  "auth.fullNamePlaceholder": { zh: "你的姓名", en: "Your name" },
  "auth.email": { zh: "邮箱", en: "Email" },
  "auth.password": { zh: "密码", en: "Password" },
  "auth.passwordPlaceholder": { zh: "至少 6 位字符", en: "At least 6 characters" },
  "auth.signin": { zh: "登录", en: "Sign In" },
  "auth.signupBtn": { zh: "注册并登录", en: "Sign Up & Sign In" },
  "auth.terms": { zh: "登录即表示同意我们的服务条款与隐私政策", en: "By signing in, you agree to our Terms and Privacy Policy" },
  "auth.signupFailed": { zh: "注册失败", en: "Sign up failed" },
  "auth.signupSuccess": { zh: "注册成功", en: "Sign up successful" },
  "auth.signinIn": { zh: "正在为你登录…", en: "Signing you in…" },
  "auth.signinFailed": { zh: "登录失败", en: "Sign in failed" },
  "auth.invalidCreds": { zh: "邮箱或密码错误", en: "Invalid email or password" },
  "auth.welcomeToast": { zh: "欢迎回来！", en: "Welcome back!" },

  // ===== Index / Landing =====
  "index.heroBadge": { zh: "你的 AI 求职伙伴", en: "Your AI Job-search Partner" },
  "index.heroTitle1": { zh: "智能求职，", en: "Smart job hunting," },
  "index.heroTitle2": { zh: "不止一份简历。", en: "more than just a resume." },
  "index.heroDesc": { zh: "上传简历、告诉偏好，系统帮你找公司、改简历、练面试，从投递到 offer 全程辅助。", en: "Upload your resume, share preferences—we find jobs, rewrite resumes, and prep interviews to land your offer." },
  "index.cta": { zh: "立即开始", en: "Get Started" },
  "index.flowTitle": { zh: "推荐 → 匹配 → 改写 → 面试", en: "Recommend → Match → Rewrite → Interview" },
  "index.flowDesc": { zh: "完整闭环，一站式搞定求职全流程", en: "One-stop full pipeline for the job search" },
  "index.step1": { zh: "上传简历", en: "Upload Resume" },
  "index.step1Desc": { zh: "支持 PDF、DOCX、TXT 格式", en: "Supports PDF, DOCX, TXT" },
  "index.step2": { zh: "智能推荐", en: "Smart Recommend" },
  "index.step2Desc": { zh: "AI 匹配最适合的岗位", en: "AI matches the best-fit jobs" },
  "index.step3": { zh: "匹配分析", en: "Match Analysis" },
  "index.step3Desc": { zh: "逐句对比简历与JD差距", en: "Sentence-level resume vs JD comparison" },
  "index.step4": { zh: "简历改写", en: "Resume Rewrite" },
  "index.step4Desc": { zh: "一键生成专属优化简历", en: "One-click optimized resume" },
  "index.step5": { zh: "模拟面试", en: "Mock Interview" },
  "index.step5Desc": { zh: "AI 面试官语音对话练到完美", en: "Voice chat with an AI interviewer" },
  "index.featuresTitle": { zh: "四大核心模块", en: "Four Core Modules" },
  "index.feat1Title": { zh: "岗位智能推荐", en: "Smart Job Recommendation" },
  "index.feat1Desc": { zh: "上传简历，AI 自动匹配最适合你的岗位，展示匹配理由与差距分析", en: "Upload your resume; AI matches the best jobs with reasons and gap analysis" },
  "index.feat2Title": { zh: "简历匹配分析", en: "Resume Match Analysis" },
  "index.feat2Desc": { zh: "逐句对比简历与JD，三色标注匹配/部分匹配/缺失，量化评分", en: "Sentence-level resume-vs-JD compare with green/yellow/red labels and scores" },
  "index.feat3Title": { zh: "智能简历改写", en: "Smart Resume Rewrite" },
  "index.feat3Desc": { zh: "3种风格一键改写，补充关键词、优化表述，实时预览提升分数", en: "3 styles, one-click rewrite, add keywords, live score preview" },
  "index.feat4Title": { zh: "面试智能辅导", en: "AI Interview Coaching" },
  "index.feat4Desc": { zh: "AI 预测面试问题，STAR框架回答建议，语音模拟面试实时评分", en: "AI predicts questions, STAR-framework tips, voice mock with real-time scoring" },
  "index.useNow": { zh: "立即使用", en: "Use Now" },
  "index.whyTitle": { zh: "为什么选择 MatchResume", en: "Why MatchResume" },
  "index.why1": { zh: "20+ 知名公司内置岗位库，即开即用", en: "Built-in jobs from 20+ top companies, ready to use" },
  "index.why2": { zh: "逐句三色标注，一眼看清匹配差距", en: "Sentence-level color labeling—see gaps at a glance" },
  "index.why3": { zh: "3 种改写风格，一键生成专属简历", en: "3 rewrite styles, one-click custom resume" },
  "index.why4": { zh: "AI 预测面试题，基于简历薄弱项", en: "AI-predicted questions targeting your weak spots" },
  "index.why5": { zh: "语音模拟面试，还原真实面试场景", en: "Voice mock interview that mirrors the real thing" },
  "index.why6": { zh: "数据看板追踪进度，越用越精准", en: "Dashboard tracks progress; gets smarter over time" },
  "index.ctaTitle": { zh: "从投递到 Offer，全程 AI 辅助", en: "From Application to Offer, AI Every Step" },
  "index.ctaDesc": { zh: "立即开始，让 AI 帮你找到最适合的工作", en: "Start now—let AI find your best-fit job" },
  "index.footer": { zh: "© 2026 MatchResume. 一站式智能求职助手。", en: "© 2026 MatchResume. One-stop AI job-search assistant." },

  // ===== Workflow Steps =====
  "workflow.jobs": { zh: "岗位推荐", en: "Jobs" },
  "workflow.match": { zh: "简历匹配", en: "Match" },
  "workflow.rewrite": { zh: "简历改写", en: "Rewrite" },
  "workflow.interview": { zh: "面试辅导", en: "Interview" },
  "workflow.tip0": { zh: "我先看看哪些岗位适合我…", en: "Let me see which jobs fit me…" },
  "workflow.tip1": { zh: "对比一下我的简历和岗位要求！", en: "Comparing my resume with the job requirements!" },
  "workflow.tip2": { zh: "改写简历，让我更有竞争力～", en: "Rewriting my resume to stand out~" },
  "workflow.tip3": { zh: "最后一关，准备好面试啦！", en: "Last step—ready for the interview!" },

  // ===== Resume Uploader =====
  "uploader.title": { zh: "上传简历", en: "Upload Resume" },
  "uploader.tooLarge": { zh: "文件大小不能超过10MB", en: "File must be smaller than 10MB" },
  "uploader.success": { zh: "简历上传成功！", en: "Resume uploaded!" },
  "uploader.failed": { zh: "上传失败", en: "Upload failed" },
  "uploader.reupload": { zh: "点击重新上传", en: "Click to re-upload" },
  "uploader.uploading": { zh: "上传中...", en: "Uploading..." },
  "uploader.click": { zh: "点击上传简历", en: "Click to upload resume" },
  "uploader.formats": { zh: "PDF、DOCX、TXT，最大10MB", en: "PDF, DOCX, TXT, max 10MB" },

  // ===== Mark Applied Button =====
  "applied.loginFirst": { zh: "请先登录后再标记投递", en: "Please sign in first to mark as applied" },
  "applied.failed": { zh: "标记失败：", en: "Failed: " },
  "applied.success": { zh: "已记录投递！数据看板会同步更新", en: "Application recorded! Dashboard will update." },
  "applied.done": { zh: "已投递", en: "Applied" },
  "applied.mark": { zh: "我已投递", en: "Mark Applied" },

  // ===== Jobs Page =====
  "jobs.title": { zh: "岗位智能推荐", en: "Smart Job Recommendation" },
  "jobs.subtitle": { zh: "上传简历，AI 自动匹配最适合你的岗位", en: "Upload your resume; AI matches the best jobs" },
  "jobs.aiMatch": { zh: "AI 智能匹配", en: "AI Match" },
  "jobs.analyzing": { zh: "分析中...", en: "Analyzing..." },
  "jobs.uploadFirst": { zh: "请先上传简历", en: "Please upload a resume first" },
  "jobs.loadFailed": { zh: "加载岗位失败", en: "Failed to load jobs" },
  "jobs.analyzeFailed": { zh: "分析失败", en: "Analysis failed" },
  "jobs.matchDone": { zh: "匹配分析完成！共评估", en: "Match analysis complete! Evaluated" },
  "jobs.matchDoneSuffix": { zh: "个岗位", en: "jobs" },
  "jobs.filters": { zh: "筛选条件", en: "Filters" },
  "jobs.searchPlaceholder": { zh: "搜索岗位/公司", en: "Search job / company" },
  "jobs.industry": { zh: "行业", en: "Industry" },
  "jobs.allIndustries": { zh: "全部行业", en: "All industries" },
  "jobs.location": { zh: "地点", en: "Location" },
  "jobs.allLocations": { zh: "全部地点", en: "All locations" },
  "jobs.jobType": { zh: "岗位类型", en: "Job type" },
  "jobs.allJobs": { zh: "全部岗位", en: "All jobs" },
  "jobs.empty": { zh: "暂无匹配的岗位", en: "No matching jobs" },
  "jobs.match": { zh: "匹配", en: "Match" },
  "jobs.yearsPlus": { zh: "年+", en: "y+" },
  "jobs.matched": { zh: "匹配：", en: "Matched: " },
  "jobs.partial": { zh: "相关：", en: "Related: " },
  "jobs.missing": { zh: "缺失：", en: "Missing: " },
  "jobs.matchAnalysis": { zh: "匹配分析", en: "Match Analysis" },
  "jobs.targetedRewrite": { zh: "针对性改写", en: "Targeted Rewrite" },
  "jobs.interviewCoach": { zh: "面试辅导", en: "Interview Coach" },
  "jobs.expReq": { zh: "经验要求", en: "Experience" },
  "jobs.eduReq": { zh: "学历要求", en: "Education" },
  "jobs.salaryRange": { zh: "薪资范围", en: "Salary" },
  "jobs.negotiable": { zh: "面议", en: "Negotiable" },
  "jobs.companySize": { zh: "公司规模", en: "Company Size" },
  "jobs.unknown": { zh: "未知", en: "Unknown" },
  "jobs.descTitle": { zh: "岗位描述", en: "Job Description" },
  "jobs.reqTitle": { zh: "任职要求", en: "Requirements" },
  "jobs.skillsTitle": { zh: "技能标签", en: "Skills" },
  "jobs.fullTime": { zh: "全职", en: "Full-time" },
  "jobs.partTime": { zh: "兼职", en: "Part-time" },
  "jobs.contract": { zh: "合同", en: "Contract" },
  "jobs.intern": { zh: "实习", en: "Intern" },
  "jobs.eduBachelor": { zh: "本科", en: "Bachelor" },
  "jobs.eduMaster": { zh: "硕士", en: "Master" },
  "jobs.eduPhd": { zh: "博士", en: "PhD" },
  "jobs.eduAssociate": { zh: "大专", en: "Associate" },
  "jobs.eduHighSchool": { zh: "高中", en: "High School" },

  // ===== Match Page =====
  "match.title": { zh: "简历-岗位匹配分析", en: "Resume–Job Match Analysis" },
  "match.subtitle": { zh: "逐句对比简历与岗位要求，三色标注匹配情况", en: "Sentence-level resume vs JD comparison with color labels" },
  "match.targetJob": { zh: "目标岗位", en: "Target Job" },
  "match.jobTitlePh": { zh: "职位名称", en: "Job title" },
  "match.companyPh": { zh: "公司名称", en: "Company name" },
  "match.jdPh": { zh: "粘贴完整岗位描述（JD）...", en: "Paste full job description (JD)..." },
  "match.startBtn": { zh: "开始匹配分析", en: "Start Match Analysis" },
  "match.analyzing": { zh: "分析中...", en: "Analyzing..." },
  "match.uploadFirst": { zh: "请先上传简历", en: "Please upload a resume first" },
  "match.jdRequired": { zh: "请输入岗位描述", en: "Please enter the job description" },
  "match.requirements": { zh: "要求：", en: "Requirements: " },
  "match.failed": { zh: "分析失败", en: "Analysis failed" },
  "match.success": { zh: "匹配分析完成！", en: "Match analysis complete!" },
  "match.placeholderTitle": { zh: "上传简历并输入目标岗位JD", en: "Upload resume and paste the target JD" },
  "match.placeholderSub": { zh: "AI 将逐句分析匹配度", en: "AI will analyze sentence by sentence" },
  "match.analyzingTitle": { zh: "AI 正在逐句分析...", en: "AI is analyzing..." },
  "match.keywordTitle": { zh: "关键词分析", en: "Keyword Analysis" },
  "match.kwMatched": { zh: "已匹配", en: "Matched" },
  "match.kwMissing": { zh: "缺失", en: "Missing" },
  "match.sentenceTitle": { zh: "逐句匹配分析", en: "Sentence-level Analysis" },
  "match.relatedReq": { zh: "对应要求：", en: "Related requirement: " },
  "match.missingTitle": { zh: "缺失项与建议", en: "Missing Items & Suggestions" },
  "match.impHigh": { zh: "高优先级", en: "High Priority" },
  "match.impMedium": { zh: "中等", en: "Medium" },
  "match.impLow": { zh: "低", en: "Low" },
  "match.nextStepTitle": { zh: "下一步：针对性改写或记录投递", en: "Next: Tailored rewrite or record application" },
  "match.nextStepDesc": { zh: "改写简历提升匹配度，或直接标记本次投递", en: "Rewrite to improve match, or mark this application" },
  "match.toRewrite": { zh: "简历改写", en: "Resume Rewrite" },

  // ===== Rewrite Page =====
  "rewrite.title": { zh: "智能简历改写", en: "Smart Resume Rewrite" },
  "rewrite.subtitle": { zh: "3种风格一键生成针对岗位的专属简历", en: "3 styles, one-click tailored resume" },
  "rewrite.settings": { zh: "改写设置", en: "Rewrite Settings" },
  "rewrite.targetTitle": { zh: "目标职位 *", en: "Target Position *" },
  "rewrite.targetCompany": { zh: "目标公司", en: "Target Company" },
  "rewrite.jdPh": { zh: "岗位描述（JD）", en: "Job description (JD)" },
  "rewrite.styleLabel": { zh: "改写风格", en: "Style" },
  "rewrite.style1": { zh: "成果导向", en: "Achievement-driven" },
  "rewrite.style1Desc": { zh: "强调量化成果和具体贡献", en: "Emphasize quantified results and contributions" },
  "rewrite.style2": { zh: "职责导向", en: "Responsibility-driven" },
  "rewrite.style2Desc": { zh: "突出管理能力和工作范围", en: "Highlight scope and management" },
  "rewrite.style3": { zh: "数据驱动", en: "Data-driven" },
  "rewrite.style3Desc": { zh: "以数据和KPI为核心叙述", en: "Center the story on data and KPIs" },
  "rewrite.startBtn": { zh: "开始改写", en: "Start Rewrite" },
  "rewrite.rewriting": { zh: "改写中...", en: "Rewriting..." },
  "rewrite.uploadFirst": { zh: "请先上传简历", en: "Please upload a resume first" },
  "rewrite.titleRequired": { zh: "请输入目标职位", en: "Please enter the target position" },
  "rewrite.success": { zh: "改写完成！", en: "Rewrite complete!" },
  "rewrite.failed": { zh: "改写失败", en: "Rewrite failed" },
  "rewrite.placeholderTitle": { zh: "上传简历，设置目标岗位和改写风格", en: "Upload resume, set target job & style" },
  "rewrite.aiRewriting": { zh: "AI 正在智能改写...", en: "AI is rewriting..." },
  "rewrite.scoreImprove": { zh: "预计匹配分提升 +", en: "Estimated score uplift +" },
  "rewrite.tabTips": { zh: "优化建议", en: "Tips" },
  "rewrite.tabCompare": { zh: "修改对照", en: "Compare" },
  "rewrite.tabFull": { zh: "完整简历", en: "Full Resume" },
  "rewrite.addedKeywords": { zh: "新增关键词", en: "Added Keywords" },
  "rewrite.original": { zh: "原文", en: "Original" },
  "rewrite.rewritten": { zh: "改写", en: "Rewritten" },
  "rewrite.changeKeywordAdd": { zh: "补充关键词", en: "Add Keywords" },
  "rewrite.changeRephrase": { zh: "重写表述", en: "Rephrase" },
  "rewrite.changeNewPoint": { zh: "新增要点", en: "New Point" },
  "rewrite.changeRemove": { zh: "删除冗余", en: "Remove" },
  "rewrite.nextStepTitle": { zh: "下一步：模拟面试准备", en: "Next: Mock Interview Prep" },
  "rewrite.nextStepDesc": { zh: "用语音和 AI 面试官练习，为面试做好准备", en: "Practice with the AI interviewer over voice" },
  "rewrite.toInterview": { zh: "面试辅导", en: "Interview Coach" },
  "rewrite.exportTxt": { zh: "TXT", en: "TXT" },
  "rewrite.exportWord": { zh: "Word", en: "Word" },
  "rewrite.exportPdf": { zh: "PDF", en: "PDF" },

  // ===== Interview Page =====
  "interview.title": { zh: "面试智能辅导", en: "AI Interview Coaching" },
  "interview.subtitle": { zh: "AI 预测面试问题、语音模拟练习、实时评分", en: "AI predicts questions, voice mock practice, real-time scoring" },
  "interview.targetTitle": { zh: "目标职位 *", en: "Target Position *" },
  "interview.targetCompany": { zh: "目标公司", en: "Target Company" },
  "interview.generateBtn": { zh: "生成面试题", en: "Generate Questions" },
  "interview.generating": { zh: "生成中...", en: "Generating..." },
  "interview.titleRequired": { zh: "请输入目标职位", en: "Please enter the target position" },
  "interview.generateSuccess": { zh: "面试题目生成完成！", en: "Questions generated!" },
  "interview.generateFailed": { zh: "生成失败", en: "Generation failed" },
  "interview.tabQuestions": { zh: "题目预测", en: "Predicted Questions" },
  "interview.tabPractice": { zh: "回答练习", en: "Practice" },
  "interview.tabMock": { zh: "语音模拟面试", en: "Voice Mock" },
  "interview.emptyHint": { zh: "点击\"生成面试题\"开始", en: "Click \"Generate Questions\" to start" },
  "interview.weaknessTitle": { zh: "基于简历薄弱项的追问", en: "Follow-ups on Resume Weak Spots" },
  "interview.commonTitle": { zh: "岗位通用高频题", en: "Common High-frequency Questions" },
  "interview.diffEasy": { zh: "简单", en: "Easy" },
  "interview.diffMedium": { zh: "中等", en: "Medium" },
  "interview.diffHard": { zh: "困难", en: "Hard" },
  "interview.practiceBtn": { zh: "练习", en: "Practice" },
  "interview.refAnswer": { zh: "参考回答框架：", en: "Reference answer framework:" },
  "interview.qSelect": { zh: "选择或输入面试问题", en: "Select or enter an interview question" },
  "interview.qPlaceholder": { zh: "输入面试问题...", en: "Enter the question..." },
  "interview.aLabel": { zh: "你的回答", en: "Your Answer" },
  "interview.aPlaceholder": { zh: "输入你的回答（建议使用STAR框架）...", en: "Enter your answer (STAR framework recommended)..." },
  "interview.evaluating": { zh: "评估中...", en: "Evaluating..." },
  "interview.aiScore": { zh: "AI 评分", en: "AI Score" },
  "interview.evalRequired": { zh: "请选择问题并输入回答", en: "Select a question and enter your answer" },
  "interview.evalFailed": { zh: "评估失败", en: "Evaluation failed" },
  "interview.dimKeyword": { zh: "关键词覆盖", en: "Keyword Coverage" },
  "interview.dimStructure": { zh: "结构完整性", en: "Structure" },
  "interview.dimQuant": { zh: "成果量化", en: "Quantification" },
  "interview.dimRelevance": { zh: "相关性", en: "Relevance" },
  "interview.strengths": { zh: "亮点", en: "Strengths" },
  "interview.improvements": { zh: "改进", en: "Improvements" },
  "interview.improvedAnswer": { zh: "优化后的回答", en: "Improved Answer" },
  "interview.mockTitle": { zh: "语音一问一答模拟面试", en: "Voice Q&A Mock Interview" },
  "interview.mockDesc": { zh: "AI 面试官将逐题提问并朗读问题，你通过麦克风语音作答。每道题回答后 AI 会即时评分，最后生成面试总结。", en: "The AI interviewer asks questions aloud; answer via microphone. Each answer is scored in real time, with a final summary." },
  "interview.startMock": { zh: "开始面试", en: "Start Interview" },
  "interview.micDenied": { zh: "麦克风权限被拒绝，请在浏览器设置中允许麦克风访问", en: "Microphone permission denied. Allow it in browser settings." },
  "interview.micDenied2": { zh: "麦克风权限被拒绝，请点击地址栏左侧的锁图标允许麦克风", en: "Microphone denied. Click the lock icon in the address bar to allow." },
  "interview.micNotFound": { zh: "未检测到麦克风设备", en: "No microphone detected" },
  "interview.micCantAccess": { zh: "无法访问麦克风：", en: "Cannot access microphone: " },
  "interview.notSupported": { zh: "浏览器不支持语音识别，请使用 Chrome", en: "Browser doesn't support speech recognition. Use Chrome." },
  "interview.noVoice": { zh: "未检测到语音内容，请重试", en: "No speech detected. Try again." },
  "interview.startFailed": { zh: "启动面试失败", en: "Failed to start interview" },
  "interview.processFailed": { zh: "处理回答失败", en: "Failed to process answer" },
  "interview.skipFailed": { zh: "跳过失败", en: "Skip failed" },
  "interview.skipped": { zh: "（跳过）", en: "(Skipped)" },
  "interview.skippedAnswer": { zh: "我选择跳过这个问题", en: "I'd like to skip this question" },
  "interview.mockEnded": { zh: "模拟面试结束，正在生成面试报告...", en: "Mock interview ended; generating report..." },
  "interview.reportFailed": { zh: "报告生成失败：", en: "Report generation failed: " },
  "interview.unknownError": { zh: "未知错误", en: "Unknown error" },
  "interview.reportTitle": { zh: "面试表现报告", en: "Interview Performance Report" },
  "interview.reportLoading": { zh: "正在生成面试表现报告...", en: "Generating performance report..." },
  "interview.dimProf": { zh: "专业知识", en: "Professional Knowledge" },
  "interview.dimComm": { zh: "沟通表达", en: "Communication" },
  "interview.dimLogic": { zh: "逻辑思维", en: "Logical Thinking" },
  "interview.dimStress": { zh: "抗压应变", en: "Stress Handling" },
  "interview.dimFit": { zh: "岗位匹配", en: "Job Fit" },
  "interview.highlights": { zh: "面试亮点", en: "Highlights" },
  "interview.toImprove": { zh: "待改进", en: "To Improve" },
  "interview.yourAnswer": { zh: "你的回答", en: "Your Answer" },
  "interview.analysis": { zh: "评析", en: "Analysis" },
  "interview.suggestedAnswer": { zh: "建议回答", en: "Suggested Answer" },
  "interview.improveTips": { zh: "改进建议", en: "Improvement Tips" },
  "interview.collapse": { zh: "收起", en: "Collapse" },
  "interview.viewSuggested": { zh: "查看建议回答与改进", en: "View suggested answer & tips" },
  "interview.overallSuggestions": { zh: "整体改进建议", en: "Overall Suggestions" },
  "interview.nextSteps": { zh: "下一步行动", en: "Next Steps" },
  "interview.restart": { zh: "重新开始", en: "Restart" },
  "interview.summary": { zh: "面试总结", en: "Interview Summary" },
  "interview.points": { zh: "分", en: " pts" },
  "interview.generateReport": { zh: "生成详细报告", en: "Generate Detailed Report" },
  "interview.questionN": { zh: "第", en: "Question " },
  "interview.questionN2": { zh: "题", en: "" },
  "interview.answered": { zh: "已答", en: "Answered " },
  "interview.questionsCount": { zh: "题 · 平均", en: " · avg " },
  "interview.endInterview": { zh: "结束面试", en: "End Interview" },
  "interview.interviewerAsk": { zh: "面试官提问", en: "Interviewer Asks" },
  "interview.replay": { zh: "重新朗读", en: "Replay" },
  "interview.readyTip": { zh: "准备好后，点击麦克风开始作答", en: "When ready, tap the mic to answer" },
  "interview.skipQ": { zh: "跳过此题", en: "Skip This Question" },
  "interview.recording": { zh: "正在录音...", en: "Recording..." },
  "interview.transcriptHint": { zh: "请开始说话，语音内容将实时显示在这里...", en: "Start speaking; transcript appears live here..." },
  "interview.tapToSubmit": { zh: "说完后点击红色按钮提交回答", en: "Tap the red button when finished to submit" },
  "interview.aiEvaluating": { zh: "AI 正在评估你的回答...", en: "AI is evaluating your answer..." },

  // ===== Dashboard =====
  "dash.title": { zh: "数据看板", en: "Dashboard" },
  "dash.subtitle": { zh: "追踪你的求职进度和优化成果（实时同步）", en: "Track your job-search progress (real-time)" },
  "dash.live": { zh: "实时", en: "Live" },
  "dash.statAnalyses": { zh: "简历分析次数", en: "Resume Analyses" },
  "dash.statAvg": { zh: "平均匹配度", en: "Avg Match" },
  "dash.statApps": { zh: "投递岗位", en: "Applications" },
  "dash.statMock": { zh: "模拟面试", en: "Mock Interviews" },
  "dash.history": { zh: "分析历史记录", en: "Analysis History" },
  "dash.loading": { zh: "加载中...", en: "Loading..." },
  "dash.empty": { zh: "暂无分析记录，去\"简历匹配\"或\"简历改写\"页面开始使用吧！", en: "No records yet. Start from Match or Rewrite!" },

  // ===== History =====
  "history.title": { zh: "历史记录", en: "History" },
  "history.subtitle": { zh: "查看过去的简历分析记录", en: "View past resume analyses" },
  "history.empty": { zh: "暂无分析记录", en: "No records" },
  "history.emptyHint": { zh: "去工作台上传简历开始分析吧", en: "Go to the workspace to start" },
  "history.scoreExcellent": { zh: "优秀", en: "Excellent" },
  "history.scoreGood": { zh: "良好", en: "Good" },
  "history.scoreNeedsWork": { zh: "待优化", en: "Needs Work" },

  // ===== NotFound =====
  "notfound.message": { zh: "页面未找到", en: "Page not found" },
  "notfound.return": { zh: "返回首页", en: "Return to Home" },

  // ===== Workspace =====
  "ws.title": { zh: "简历优化工作台", en: "Resume Optimization Workspace" },
  "ws.subtitle": { zh: "上传简历，AI 智能分析并提供优化建议", en: "Upload your resume; AI analyzes and suggests improvements" },
  "ws.uploadTitle": { zh: "上传简历", en: "Upload Resume" },
  "ws.fileSize": { zh: "文件大小不能超过10MB", en: "File must be smaller than 10MB" },
  "ws.uploadFirst": { zh: "请先上传简历文件", en: "Please upload a resume file first" },
  "ws.titleFirst": { zh: "请输入期望职位", en: "Please enter the desired position" },
  "ws.success": { zh: "分析完成！", en: "Analysis complete!" },
  "ws.failed": { zh: "分析失败，请重试", en: "Analysis failed; please retry" },
  "ws.clickUpload": { zh: "点击上传简历文件", en: "Click to upload resume" },
  "ws.formats": { zh: "支持 PDF、DOCX、TXT 格式，最大 10MB", en: "Supports PDF, DOCX, TXT, max 10MB" },
  "ws.targetJob": { zh: "目标职位", en: "Target Position" },
  "ws.desiredTitle": { zh: "期望职位 *", en: "Desired Position *" },
  "ws.titlePh": { zh: "如：前端工程师", en: "e.g. Frontend Engineer" },
  "ws.companyLabel": { zh: "目标公司", en: "Target Company" },
  "ws.companyPh": { zh: "如：Google", en: "e.g. Google" },
  "ws.jdLabel": { zh: "职位描述（可选）", en: "Job Description (optional)" },
  "ws.jdPh": { zh: "粘贴完整的职位描述，AI 将更精准匹配...", en: "Paste full JD for more accurate match..." },
  "ws.startBtn": { zh: "开始分析", en: "Start Analysis" },
  "ws.analyzing": { zh: "AI 分析中...", en: "AI analyzing..." },
  "ws.placeholderTitle": { zh: "上传简历并填写目标职位", en: "Upload resume and fill in target position" },
  "ws.placeholderSub": { zh: "AI 将为你生成详细的匹配分析报告", en: "AI will generate a detailed match report" },
  "ws.aiTitle": { zh: "AI 正在分析你的简历...", en: "AI is analyzing your resume..." },
  "ws.aiSub": { zh: "这可能需要 30 秒左右", en: "This may take ~30 seconds" },
  "ws.matchScore": { zh: "匹配度评分", en: "Match Score" },
  "ws.dimensions": { zh: "维度分析", en: "Dimension Analysis" },
  "ws.suggestions": { zh: "优化建议", en: "Suggestions" },
  "ws.optimizedContent": { zh: "优化后简历内容", en: "Optimized Resume Content" },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  toggle: () => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType>({
  lang: "zh",
  setLang: () => {},
  toggle: () => {},
  t: (k) => k,
});

const STORAGE_KEY = "matchresume.lang";

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === "undefined") return "zh";
    const saved = localStorage.getItem(STORAGE_KEY) as Lang | null;
    return saved === "en" || saved === "zh" ? saved : "zh";
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang === "zh" ? "zh-CN" : "en";
  }, [lang]);

  const setLang = (l: Lang) => setLangState(l);
  const toggle = () => setLangState((p) => (p === "zh" ? "en" : "zh"));
  const t = (key: string) => {
    const entry = dict[key];
    if (!entry) return key;
    return entry[lang];
  };

  return (
    <LangContext.Provider value={{ lang, setLang, toggle, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLanguage = () => useContext(LangContext);
